apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workmate

configMapGenerator:
  - name: env
    envs:
      - .env
  - name: swagger-ui-cm0
    files:
      - docs/swagger.json
  - name: web-cm0
    files:
      - .docker/conf/Caddyfile

resources:
  - .kustomize/app
  - .kustomize/db
  - .kustomize/swagger-ui
  - .kustomize/web